#!/usr/bin/env ruby

require 'byebug'
require 'pathname'
path = Pathname.new(__FILE__)
$:.unshift File.expand_path "../../lib/", path.realpath
require 'problematic_variable_finder'



ProblematicVariableFinder.run

